Feat 38080573 filter sets
dodopizza/superset pull request #170
Opened 2024-11-12 12:20 UTC by artem12345-png

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2024-11-19 02:49 UTC, LiamTorrelli requested changes

2024-11-19 02:49 UTC, LiamTorrelli commented on superset-frontend/src/dashboard/actions/nativeFilters.ts
> +  };;
какая-то странная штука @etokiryau

2024-11-19 06:01 UTC, pa1ch requested changes

2024-11-19 08:06 UTC, etokiryau commented on superset-frontend/src/dashboard/actions/nativeFilters.ts
> +  };;
Убрал лишний код

2024-11-27 06:11 UTC, LiamTorrelli approved these changes

2024-11-28 07:11 UTC, merged