Release v.3.0.0 1.1.3
dodopizza/superset pull request #171
Opened 2024-11-13 07:13 UTC by etokiryau

2024-11-14 11:11 UTC, pa1ch commented on superset/charts/data/api.py
> +                    if language == "ru":
а для en?

2024-11-19 05:04 UTC, artem12345-png commented on superset/charts/data/api.py
> +                    if language == "ru":
Убрал вообще проверку на язык, так как независимо от языка у нас в metric map будут название метрик в зависимости от языка, так как они приходят с фронта, поэтому если будет русский мы сделаем rename на русский, если будет английский, то сделаем rename на английский

2024-11-20 05:01 UTC, pa1ch requested changes

2024-11-20 05:01 UTC, pa1ch commented on superset/views/utils.py
> +    return 'ru'
Используй всегда двойные кавычки. Этот стандарт задал линтер black. У нас в проекте ruff и он тоже настроен на двойные кавычки

2024-11-20 05:41 UTC, artem12345-png commented on superset/views/utils.py
> +    return 'ru'
ага, хорошо, сейчас поправлю

2024-11-20 05:45 UTC, pa1ch approved these changes

2024-11-20 09:56 UTC, merged