Перенос переводов
dodopizza/superset pull request #63
Opened 2024-03-14 11:00 UTC by artem12345-png

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2024-03-15 03:17 UTC, LiamTorrelli requested changes

2024-03-15 03:17 UTC, LiamTorrelli commented on docker-compose.yml
> +   platform: linux/amd64
это надо убрать. потому что в 3.0 все уже четко выровнено

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/charts/api.py
> +        "primary_lang",
а зачем нам поле primary_lang?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/connectors/base/models.py
> +    description_EN = Column(Text, nullable=True, default=None)
зачем нам description_EN? мы не дублицируем поле description на два языка

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/connectors/base/models.py
> +            "description_EN",
зачем нам description_EN? мы не дублицируем поле description на два языка

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/connectors/base/models.py
> +    description_EN = Column(Text, nullable=True, default=None)
зачем нам description_EN? мы не дублицируем поле description на два языка

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/connectors/base/models.py
> +            "description_EN",
зачем нам description_EN? мы не дублицируем поле description на два языка

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +        get_last_modified=lambda _self,
а это изменение зачем?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +        get_last_modified=lambda _self,
а это изменение зачем?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +        get_last_modified=lambda _self,
а это изменение зачем?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +                                             f".favorite_status",
а это изменение зачем?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +                                             f".add_favorite",
а это изменение зачем?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +                                             f".remove_favorite",
а это изменение зачем?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +        action=lambda self, *args,
а это изменение зачем?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/schemas.py
> +    dashboard_title_RU = fields.String(description=dashboard_title_description)
не понимаю, что это?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/dashboards/schemas.py
> +    dashboard_title_RU = fields.String(description=dashboard_title_description)
не понимаю, что это?

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/datasets/api.py
> +        "columns.description_EN",
убрать поле decriptionEN

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/datasets/api.py
> +        "metrics.description_EN",
убрать поле decriptionEN

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/datasets/schemas.py
> +    description_EN = fields.String(allow_none=True)
убрать поле decriptionEN

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/datasets/schemas.py
> +    description_EN = fields.String(allow_none=True)
убрать поле decriptionEN

2024-03-15 03:17 UTC, LiamTorrelli commented on superset/models/slice.py
> +    primary_lang = Column(Text, nullable=True)
убрать поле primary_lang

2024-03-15 06:29 UTC, artem12345-png commented on superset/charts/api.py
> +        "primary_lang",
оно было, поэтому я его и добвил

2024-03-15 06:29 UTC, artem12345-png commented on superset/dashboards/api.py
> +        get_last_modified=lambda _self,
так ничего же не поменялось, просто немного съехало

2024-03-15 06:29 UTC, artem12345-png commented on superset/dashboards/schemas.py
> +    dashboard_title_RU = fields.String(description=dashboard_title_description)
это поле для валидации при получении дашборда

2024-03-15 06:29 UTC, artem12345-png commented on superset/dashboards/schemas.py
> +    dashboard_title_RU = fields.String(description=dashboard_title_description)
это я добавил поле для валидации при put запросе

2024-03-15 06:29 UTC, artem12345-png commented on docker-compose.yml
> +   platform: linux/amd64
если и тут нормально и в 3.0 нормально, то и будет нормально

2024-03-15 06:31 UTC, LiamTorrelli requested changes

2024-03-15 06:31 UTC, LiamTorrelli commented on docker-compose.yml
> +   platform: linux/amd64
в прошлый раз у меня из-за этих изменений не собиралось ничего, так как yaml файл очень зависит от отступов.

2024-03-15 06:32 UTC, LiamTorrelli requested changes

2024-03-15 06:32 UTC, LiamTorrelli commented on superset/dashboards/api.py
> +        get_last_modified=lambda _self,
каждое твое изменение, которое ты вносишь, его надо поддерживать. и не хочется, чтобы такие изменения надо будет потом переносить и могут быть конфликты и тд. поэтому все изменения по стилингу убери

2024-03-15 06:47 UTC, LiamTorrelli approved these changes

2024-03-20 06:27 UTC, LiamTorrelli requested changes

2024-03-20 06:27 UTC, LiamTorrelli commented on superset/common/chart_data.py
> +class ChartDataResultLanguage(StrEnum):
у нас эти языки есть в config.py. мб оттуда их будем брать, чтобы не было две одинаковые сущности?

2024-03-20 06:27 UTC, LiamTorrelli commented on superset/viz.py
>      @deprecated(deprecated_in="3.0")
что именно тут будет deprecated in 3.0?

2024-03-20 06:27 UTC, LiamTorrelli commented on superset/viz.py
>      @deprecated(deprecated_in="3.0")
что именно тут будет deprecated in 3.0?

2024-03-20 06:39 UTC, artem12345-png commented on superset/viz.py
>      @deprecated(deprecated_in="3.0")
сам метод deprecated, но в коде он еще используется, посмотрим как они потом его заменят

2024-03-20 06:39 UTC, artem12345-png commented on superset/viz.py
>      @deprecated(deprecated_in="3.0")
тоже самое как и в get_csv

2024-03-20 06:39 UTC, artem12345-png commented on superset/common/chart_data.py
> +class ChartDataResultLanguage(StrEnum):
Попробую это сделать, но не факт что получиться

2024-03-20 06:42 UTC, LiamTorrelli requested changes

2024-03-20 06:42 UTC, LiamTorrelli commented on superset/common/chart_data.py
> +class ChartDataResultLanguage(StrEnum):
надо это сделать, обязательно

2024-03-21 05:09 UTC, artem12345-png commented on superset/common/chart_data.py
> +class ChartDataResultLanguage(StrEnum):
Лучше оставить это так, так как не получится из словаря проинициировать значения для класса

2024-03-21 05:09 UTC, artem12345-png commented on superset/dashboards/api.py
> +            if language == "ru":
А вот тут я понял, что можно как раз от того класса сделать проверку какой язык пришел, а не тупо хардкодить
И точно так же в других местах

2024-03-21 05:09 UTC, artem12345-png commented on superset/dashboards/api.py
> +            if language == "ru":
вот тут например

2024-03-21 05:09 UTC, artem12345-png commented on superset/views/core.py
> +            if language == "ru":
и тут

2024-04-09 04:43 UTC, merged