#29139342 Фриз столбца в таблице
dodopizza/superset pull request #67
Opened 2024-04-11 07:14 UTC by michael-916310

task: https://dodopizza.kaiten.ru/space/306493/card/29139342

2024-04-11 08:56 UTC, LiamTorrelli requested changes

2024-04-11 08:56 UTC, LiamTorrelli commented on superset-frontend/plugins/plugin-chart-table/src/DodoExtensions/DataTable/hooks/useStickyDodo.tsx
> +import getScrollBarSize from '../../../DataTable/utils/getScrollBarSize';
лучше использовать абсолютный путь

2024-04-11 08:56 UTC, LiamTorrelli commented on superset-frontend/plugins/plugin-chart-table/src/DodoExtensions/TableChartDodo.tsx
Надо по примеру с Big Number сделать максимальное переиспользование кода из TableChart

2024-04-11 08:56 UTC, LiamTorrelli commented on superset-frontend/plugins/plugin-chart-table/src/DodoExtensions/DataTable/hooks/useStickyDodo.tsx
надо по примеру с Big Number сделать максимальное переиспользование кода

2024-04-11 08:56 UTC, LiamTorrelli commented on superset-frontend/packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts
> +function hexToRgb(hex: string) {
давай эти две функции вынесем в какой-нить util файл, там проведем всю калькуляцию и сюда уже вернем значение финальное

2024-04-11 09:37 UTC, michael-916310 commented on superset-frontend/plugins/plugin-chart-table/src/DodoExtensions/DataTable/hooks/useStickyDodo.tsx
Тут так не сделаю, как-то уже очень сложно они вызываются. В этом файле всего 2 измнения:
- объявление контекста
- пробрасыванеи контекста
Можем перенести в оригинальный, этот удалить.

Хотя наличие этого отдельного файла позволяет в любом он-лайн сравнитете файлов ( https://pautina.io/sravnit-kod/ )  увидеть что мы меняли относительно оригинала, что тоже удобно

2024-04-11 11:34 UTC, michael-916310 commented on superset-frontend/plugins/plugin-chart-table/src/DodoExtensions/TableChartDodo.tsx
Кое что сделал - экспортнул из оригинального файла и импортнул в новом. Но основная функция не особо экстендится. Думаю это максимум тут.

2024-04-11 11:46 UTC, michael-916310 commented on superset-frontend/plugins/plugin-chart-table/src/DodoExtensions/DataTable/hooks/useStickyDodo.tsx
Добавил экспорт всего что можно из оригинального файла и импорт в новый

2024-04-11 11:47 UTC, michael-916310 commented on superset-frontend/plugins/plugin-chart-table/src/DodoExtensions/DataTable/hooks/useStickyDodo.tsx
> +import getScrollBarSize from '../../../DataTable/utils/getScrollBarSize';
здесь лучше как раз относительный, поскольку абсолютный сторится от каталога src, а тут plugins на уровне src

2024-04-12 03:35 UTC, LiamTorrelli requested changes

2024-04-12 03:35 UTC, LiamTorrelli commented on superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
> +// function StickyWrap({
наверное надо бы почистить этот закоментированный код

2024-04-12 04:21 UTC, michael-916310 commented on superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx
> +// function StickyWrap({
это код оригинальной функции
хотелось бы его оставить, чтобы было с чем сравнивать

закомментировал, т.к. для линтера не используаемая переменная была ошибкой,

2024-04-12 04:25 UTC, merged