33067895 Перевод фильтров в дашборде
dodopizza/superset pull request #81
Opened 2024-05-03 09:59 UTC by michael-916310

2024-05-06 02:45 UTC, LiamTorrelli requested changes

2024-05-06 02:45 UTC, LiamTorrelli commented on superset-frontend/plugins/legacy-preset-chart-nvd3/src/DodoExtensions/NVD3Vis.js
> +      chart.xDomain(computeStackedXDomain(data));
а эта правка тут для какой задачи?

2024-05-07 07:19 UTC, michael-916310 commented on superset-frontend/plugins/legacy-preset-chart-nvd3/src/DodoExtensions/NVD3Vis.js
> +      chart.xDomain(computeStackedXDomain(data));
это мой косяк с прошлой задачи по доработке баблчарта
только сейчас заметил

2024-05-07 07:27 UTC, michael-916310 commented on superset-frontend/plugins/legacy-preset-chart-nvd3/src/NVD3Vis.js
> +// const formatter = getNumberFormatter();
убрал

2024-05-07 07:32 UTC, merged